### ISSUE TITLE
Multiple OpsGenie sinks override one another

### ISSUE THREAD

**Issue by arikalon1** [robusta-dev/robusta#1018]
When configuring multiple OpsGenie sinks, with different api keys, directed to different OpsGenie sinks, the sinks configuration override one another.

An example configuration:
```
  sinksConfig:
    - slack_sink:
        name: main_slack_sink
        slack_channel: prod-alerts
        api_key: <REDACTED>
    - opsgenie_sink:
        name: devops_ops_genie_sink
        api_key: <REDACTED>
        match:
          labels:
            - "team=devops"
    - opsgenie_sink:
        name: dev_ops_genie_sink
        api_key: <REDACTED>
        match:
          labels:
            - "team=dev"
``` 

When creating an alert with label `team=devops` it's matched by the correct sink, `devops_ops_genie_sink`, but sent using the api client of the other sink, which is delivered to the wrong OpsGenie team
