### ISSUE TITLE
Feature Request: Multiple alerts in on_prometheus_alert trigger

### ISSUE THREAD

**Issue by otherguy** [robusta-dev/robusta#1049]
It would be great if the `on_prometheus_alert` trigger supported multiple alert names as a comma separated string or an array. E.g.:

```
- triggers:
    - on_prometheus_alert:
        alert_name: [ MyCustomCPUAlert, MyCustomMemoryAlert, MyCustomDiskAlert ]
  actions:
    - default_enricher: {}
```

**Comment by arikalon1** [comment]
Hi @otherguy 

You can do it this way:
```
- triggers:
    - on_prometheus_alert:
        alert_name:  MyCustomCPUAlert
    - on_prometheus_alert:
        alert_name:  MyCustomMemoryAlert
    - on_prometheus_alert:
        alert_name:  MyCustomDiskAlert
  actions:
    - default_enricher: {}
```

Given the above, do you still need the array option?

**Comment by otherguy** [comment]
Hey @arikalon1 and thanks for the explanation! No, I believe this covers our use case nicely.

Is it also possible to enrich an alert in multiple triggers, and if so, does it follow the order defined in the configuration?

Eg:

```yaml
- triggers:
    - on_prometheus_alert:
        alert_name:  MyCustomCPUAlert
    - on_prometheus_alert:
        alert_name:  MyCustomMemoryAlert
    - on_prometheus_alert:
        alert_name:  MyCustomDiskAlert
  actions:
    - default_enricher: {}

- triggers:
    - on_prometheus_alert:
        alert_name:  MyCustomCPUAlert
  actions:
    - some_other_enricher: {}
```
