### ISSUE TITLE
Robusta is not able to route based on labels

### ISSUE THREAD

**Issue by volver-13** [robusta-dev/robusta#1108]
**Describe the bug**
Robusta is not able to route based on labels

**To Reproduce**
I have the following sinks configuration:

```yaml
sinksConfig:
- ms_teams_sink:
    name: main_ms_teams_sink_product_a
    webhook_url: xxxx
    match:
      labels: "business=product_a"
- ms_teams_sink:
    name: main_ms_teams_sink_product_b
    webhook_url: xxxx
    match:
      labels: "business=product_b"
- ms_teams_sink:
    name: main_ms_teams_sink_default
    webhook_url: xxxxx
    match:
      severity: [INFO, LOW, MEDIUM, HIGH]
- opsgenie_sink:
    name: opsgenie_sink
    api_key: <opsgenie_sink_token>
    teams:
    - "SRE-TEAM"
    tags:
    - "application-cluster"
- robusta_sink:
    name: robusta_ui_sink
    token: <robusta_sink_token>
```

**Expected behavior**
Alerts are routed towards correct MS teams channels, instead all the alert gets routed into default channel `main_ms_teams_sink_default`

**Robusta version (please complete the following information):**
I'm running latest robusta version 0.10.24

**Context**
The alerts are coming from Alert Manager and they have proper labels visible in Prometheus Alert Manager UI
