### ISSUE TITLE
Robusta does not include tags when posting alerts to OpsGenie sink

### ISSUE THREAD

**Issue by volver-13** [robusta-dev/robusta#1109]
### Describe the bug
Robusta does not include tags when posting alerts to OpsGenie sink

### To Reproduce
I have the following sinks configuration:

```yaml
sinksConfig:
- ms_teams_sink:
    name: main_ms_teams_sink_product_a
    webhook_url: xxxx
    match:
      labels: "business=product_a"
- ms_teams_sink:
    name: main_ms_teams_sink_product_b
    webhook_url: xxxx
    match:
      labels: "business=product_b"
- ms_teams_sink:
    name: main_ms_teams_sink_default
    webhook_url: xxxxx
    match:
      severity: [INFO, LOW, MEDIUM, HIGH]
- opsgenie_sink:
    name: opsgenie_sink
    api_key: <opsgenie_sink_token>
    teams:
    - "SRE-TEAM"
    tags:
    - "application-cluster"
- robusta_sink:
    name: robusta_ui_sink
    token: <robusta_sink_token>
```

### Expected behavior
Sink configured acording to [documentation](https://docs.robusta.dev/master/catalog/sinks/Opsgenie.html)
Alerts are posted to OpsGenie with `application-cluster` tag. 

### Actual behavior
Unfortunately `application-cluster` is not included in the alerts in OpsGenie

### Robusta version (please complete the following information):
I'm running latest robusta version 0.10.24
