### ISSUE TITLE
Service monitor doesnt report to Robusta UI when external prometheus is installed.

### ISSUE THREAD

**Issue by tip-dteller** [robusta-dev/robusta#1114]
**Describe the bug**
Prometheus: Not installed using Robusta, Its external in Monitoring Namespace.
When tapping Robusta Runner in UI, you dont see any metrics and insights for the robusta runner, see image.
<img width="1368" alt="image" src="https://github.com/robusta-dev/robusta/assets/128965284/8b21a800-4215-4aed-b6ad-c7dcdd5c758d">

**To Reproduce**
1. Install external prometheus
2. Install Robusta
3. Go to UI in Robusta and select Robusta-Runner

**Expected behavior**
I should see metrics and stuff :)

Here's the FIX:
The problem lies in the ServiceMonitor yaml definition.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robusta-runner-service-monitor
  labels:
    # this label is how the Prometheus installed with Robusta finds ServiceMonitors
    # TODO: we probably need to add custom labels here for a Prometheus installed separately
    release: {{ .Release.Name }}
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: {{ .Release.Name }}-runner
  targetLabels:
    - target <- This is the problem
```

The target label doesnt exist. hence it cannot do anything.
the fix is to change target to App.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robusta-runner-service-monitor
  labels:
    # this label is how the Prometheus installed with Robusta finds ServiceMonitors
    # TODO: we probably need to add custom labels here for a Prometheus installed separately
    release: {{ .Release.Name }}
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: {{ .Release.Name }}-runner
  targetLabels:
    - app <- the fix

```
