### ISSUE TITLE
[helm] [forwarder] impossible to mount the service account token manually when automountServiceAccountToken is set to false

### ISSUE THREAD

**Issue by michMartineau** [robusta-dev/robusta#1155]
**Describe the bug**
If the chart value `automountServiceAccountToken` is set to false for security reason. The forwarder doesn't start.
It is not possible to mount manually the token

**To Reproduce**
1. set the chart value `automountServiceAccountToken: false`
2. apply the change (flux, helm upgrade....)
3. the forwarder doesn't start

Note: the runner starts but it is not functional. but it is possible to fix that it we mount manually the token volume.
```
    runner:
      extraVolumes:
        - name: sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3607
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
      extraVolumeMounts:
        - name: sa-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount/
          readOnly: true
```

**Expected behavior**
We would like to have the possibility to mount the sa token manually with the following configuration
```
    kubewatch:
      extraVolumes:
        - name: sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3607
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
      extraVolumeMounts:
        - name: sa-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount/
          readOnly: true
```
**Additional context**
A pr has been created in order to add extraVolumes and extraVolumeMounts possibility: https://github.com/robusta-dev/robusta/pull/1154
