### ISSUE TITLE
Rate limit feature for on_kubernetes_warning_event

### ISSUE THREAD

**Issue by otherguy** [robusta-dev/robusta#1173]
We sometimes have GCP acting up and causing false positives in our alerts.Currently this is our configuration, but sometimes we still get false positives.

```
- triggers:
  - on_kubernetes_warning_event_create:
      include: [ "FailedGetPodsMetric", "FailedGetExternalMetric" ]
      exclude: [ "googleapi: Error 503", "googleapi: Error 429", "No recommendation" ]
```

Some time ago, [@Avi](https://robustacommunity.slack.com/team/U02STMP43AT) built a custom image to test a few additional options to the trigger:

-   `rate_limit`
-   `min_count`
-   `delay_s`

But I don't see those in the documentation, so they probably never made it into a release.It would be great if those could be included and e.g. have the warning event only trigger if the Kubernetes Warning event has been firing for a certain length of time, or has fired a certain amount of times.
