### ISSUE TITLE
`mention_enricher` do not work correctly using labels

### ISSUE THREAD

**Issue by kristeey** [robusta-dev/robusta#1279]
**Describe the bug**
`mention_enricher` have (as of now) two possible methods to mention slack users/teams in the slack messanges. 1. `static_mentions` that are explicitly set in the custom playbook. 2. `mentions_label` value set in custom playbook config that specify a label/annotation on K8S resources where the value of this label/annotation will be used to mention slack users/teams.

This works fine for `static_mentions` and `mention_label` using k8s annotations when the values are on the form `@user-nick`, `<@U....> `(for users) , `<!subteam^...> `(for slack groups). 

Problem: 
This logic do not work when we use `mention_label` with k8s labels, because k8s labels value do not accept special characters such as `<`and `@` ad the syntax is: 

```
Valid label value:

- must be 63 characters or less (can be empty),
- unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
- could contain dashes (-), underscores (_), dots (.), and alphanumerics between.
```

**To Reproduce**
1. In helm chart write:

```
 customPlaybooks:
    - triggers:
      - on_pod_crash_loop: {}
      actions:
        - mention_enricher:
            mentions_label: "slackAlertMentions"
```
2. In deployment of a crashing pod add the label
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        slackAlertMentions: "@some-user"                      # or "<@U....>"
        app: crash-loop
    spec:
      containers:
      - name: crashing-container
        image: nginx
        command: ["sh", "-c", "command_not_found"]
```

3. Apply deployment:
`kubectl apply -f crashloopbackoff-deployment.yaml`
```
The Deployment "crash-loop" is invalid: spec.template.labels: Invalid value: "@some-user": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

** Comments**
This isn't Robusta fault per se, as this is limited by the labeling syntax in k8s. But if you want to support `mention_enricher` using labels one should handle this by setting the user ID or user nick on the correct format in the action it self, or not support labels at all, as it works fine for annotations and static mentions
