### ISSUE TITLE
Getting multiple reports krr when set for a specific time

### ISSUE THREAD

**Issue by ShibraAmin** [robusta-dev/robusta#1280]
**Describe the bug**
getting 2 reports when I have set a cron_expression: "00 4 * * 2" for krr 
```
2024-01-30 03:59:02.001 INFO     running scheduled job 970bfc78c2d90a4264f8d4afd7512666
2024-01-30 04:01:50.215 INFO     running scheduled job 970bfc78c2d90a4264f8d4afd7512666 
```

**To Reproduce**
Install robusta in a kubernetes cluster with following `customPlaybooks` section in your `generated_values.yaml`

```
customPlaybooks:
  - triggers:
      - on_schedule:
          cron_schedule_repeat:
            cron_expression: "00 4 * * 2"
    actions:
      - krr_scan:
          krr_args: "--history_duration 168" ## KRR args here
    sinks:
      - "sink_a"
```

**Expected behavior**
To get a report at `00 4 * * 2` with a single job scheduled in runner.

**Additional context**
Kubernetes -> EKS 1.22
Robusta chart version -> 0.10.27
