### ISSUE TITLE
At least one sink must be defined - Using ArgoCD

### ISSUE THREAD

**Issue by AlissonRS** [robusta-dev/robusta#1357]
I used robusta CLI to generate a `generated_values.yaml` for me.

This is how it looks:

```
globalConfig:
  signing_key: <some_guid>
  account_id: <some_guid>
sinksConfig:
  - discord_sink:
      name: personal_discord_sink
      url: https://discord.com/api/webhooks/123456789
disableCloudRouting: true
runner:
  sendAdditionalTelemetry: true
clusterName: my-cluster
```

So it does have a sink (using my actual webhook URL), but installing it with Helm via ArgoCD produces the error below:

>  failed exit status 1: Error: execution error at (Robusta/charts/robusta/templates/playbooks-config.yaml:9:7): At least one sink must be defined! Use --debug flag to render out invalid YAML

From Argo UI we can see the parameter is detected (so it's properly formatted):

![image](https://github.com/robusta-dev/robusta/assets/4753901/d234aa40-5e09-45b6-bca5-9aeeae811ea6)

If I install the exact same `values.yaml` via helm CLI from my local machine, it works fine, it's only failing via Argo.

Not sure if it makes a difference, but it's actually being installed as a subchart as I'm using Argo's ApplicationSet.
