### ISSUE TITLE
Grafana annotations don't work?

### ISSUE THREAD

**Issue by nice-pink** [robusta-dev/robusta#1410]
**Describe the bug**
I set up the `add_pdeployment_lines_to_grafana` in `values.yaml` but can't get it running. I might have misconfigured it.

**To Reproduce**
This is the relevant part of the `values.yaml`.

The slack notifications work, but the annotations don't.

```
customPlaybooks:
- triggers:
    - on_pod_crash_loop: {}
    - on_pod_oom_killed: {}
    - on_container_oom_killed: {}
    # - on_deployment_update: {}
  actions:
    - resource_babysitter: {}
  sinks:
    - slack
- triggers:
    - on_daemonset_all_changes: {}
    - on_statefulset_all_changes: {}
    - on_daemonset_all_changes: {}
    - on_pod_create: {}
    - on_pod_delete: {}
  actions:
    - add_deployment_lines_to_grafana:
        grafana_api_key: "{{ env.GRAFANA_API_KEY }}"
        grafana_dashboard_uid: GRAFANA_DASHBOARD_ID
        grafana_url: "http://grafana.ops.svc.cluster.local:80"
        cluster_name: "{{ env.CLUSTER_NAME }}"
```

**Expected behavior**
I don't see any annotations (deployment_lines) in the dashboard.

**Desktop (please complete the following information):**
 - Grafana V8
 - Robusta 0.12.0
