### ISSUE TITLE
Multiples Teams Sink does not works as expected

### ISSUE THREAD

**Issue by antikilahdjs** [robusta-dev/robusta#1456]
**Describe the bug**
Hello all.

It is possible Robusta works with 2 or more Teams sink as well? I am facing some issues and the alerts like medium/low is not reach me out.  I do not know why , but just the debug works as well. For the high condition is never is routed to another sink like my yaml below

My configuration is 

```yaml
sinksConfig:
- ms_teams_sink:
    name: main_ms_teams_sink_general
    webhook_url: myteamshook1
    match:
      severity: [LOW, MEDIUM, DEBUG]
    default: true
- ms_teams_sink:
    name: main_ms_teams_sink_critical
    webhook_url: myteamshook2
    scope:
      exclude:
        - labels: "app/ioxxxxx.*"
    match:
      severity: [HIGH]
    default: false
```

**To Reproduce**
1. Add the sink like described
2. Install the helm as well

**Expected behavior**
If possible I would like to know how to configure to works correctly it because I had tried many approach.

If I configure just the single SINK it works normally 

**Screenshots**
