### ISSUE TITLE
[Feature] Add the posibility to create tables in the create_finding action

### ISSUE THREAD

**Issue by crileroro** [robusta-dev/robusta#1520]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Currently I am using the action `create_finding`. I would like to have a way to create tables in the `description`. Something around the lines of: 
```
actions:
      - create_finding:
          title: 'Workflow $labels.workflow_name failed'
          aggregation_key: WorkflowFailures
          severity: HIGH
          description: |
             # Following is a pseudocode of a table creation
             | workflow name | namespace | severity|
             ----
             | $labels.workflow_name | $labels.namespace | HIGH | 
```

**Additional context**
Would be nice to have this and more features from markdown in order to enrich further the description in my `create_finding` action
