### ISSUE TITLE
NoData using Teams using pod_node_graph_enricher

### ISSUE THREAD

**Issue by antikilahdjs** [robusta-dev/robusta#1527]
**Describe the bug**
Hello, the pod_node_graph_enricher send noData to my Teams as well. The memory for Container and Pods works perfectly. 

**To Reproduce**
1. Install the Robusta using the normal way (Helm Charts)
2. Add the custom values like
```yaml
# Critical Events (Custom)
- triggers:
  - on_pod_oom_killed:
      rate_limit: 3600
  actions:
  - pod_oom_killer_enricher: {}
  - logs_enricher: {}
  - pod_node_graph_enricher:
      resource_type: Memory
      display_limits: false
  - oomkilled_container_graph_enricher:
      resource_type: Memory
      display_limits: true
  - pod_graph_enricher:
      resource_type: Memory
      display_limits: true
  sinks:
    - "main_ms_teams_sink_critical"
  stop: true
```
4. Change memory_limits to false as above

**Expected behavior**
Do not display the Node Memory Limits or show the Memory correctly because for now always it is sent with "No Data"

**Screenshots**
![image](https://github.com/user-attachments/assets/77c0276a-4323-4511-8135-031f6b704c2d)

**Additional context**
If the value is true or false the alerts sent to the Teams with No Data, does matter what you configure
