### ISSUE TITLE
Add labels as variables for foreign_logs_enricher

### ISSUE THREAD

**Issue by balzat** [robusta-dev/robusta#1529]
**Is your feature request related to a problem?**
For foreign_logs_enricher it is not currently available to use labels as variables. It would be very useful to have this capability to create flexible playbooks.

**Describe the solution you'd like**
Add the capability to use the labels/annotations in the template.

```
customPlaybooks:
  - name: "ServiceLogErrors"
    triggers:
    - on_prometheus_alert:
        alert_name: ServiceLogErrors
    actions:
    - foreign_logs_enricher:
        label_selectors:
          - 'app=$labels.service'
        warn_on_missing_label: True
```
