### ISSUE TITLE
New Sink: Telegram

### ISSUE THREAD

**Issue by tuananh2508** [robusta-dev/robusta#165]
**Describe the solution you'd like**
Telegram is a very famous tool right now for sending alerting and I think that It would be very handy if Telegram Sink is supported

**Comment by aantn** [comment]
Yes, we can add it!

Would you be able to help beta test this?

**Comment by tuananh2508** [comment]
Absolutely

**Comment by aantn** [comment]
Cool, it'll be another few days before it's ready. I'll let you know here.

Which Robusta features are you most interested in? I'll make sure we test those specific features on our end specifically for the Telegram integration.

**Comment by tuananh2508** [comment]
@aantn Aside from the basic things, I think the "ChatOps" feature is pretty cool.

**Comment by aantn** [comment]
@tuananh2508 Cool, that helps. It means we'll need to add support for the Telegrama sink for two-way-interactivity.

@arikalon1 FYI

**Comment by tuananh2508** [comment]
Yeah tks, but the most important things to us is still the core function of Robusta - Alerting :D. Hope that feature is going to be release soon.

**Comment by aantn** [comment]
Got it, so it would be OK do this in two parts, right?

Part 1: send messages to Telegram without two-way interactivity

Part 2: enable the fix buttons with two-way interactivity

**Comment by tuananh2508** [comment]
Yes, love it. I will try to be most supportive for this feature

**Comment by tuananh2508** [comment]
Thanks for all the hard work. We're on holiday so I will report the result or any bugs next week.

**Comment by arikalon1** [comment]
Gladly. We'd love to hear any feed back you have.

**Comment by tuananh2508** [comment]
![image](https://user-images.githubusercontent.com/66721505/153131619-a06098a8-65ae-4068-8810-ef5a41bc75e5.png)
I'm trying `resource_babysitter` actions. But look like when I update deployment replicas, robusta doesn't notify that to me

**Comment by tuananh2508** [comment]
![image](https://user-images.githubusercontent.com/66721505/153135935-e01ff5f3-ce84-41c3-9e35-e90dcfd69bdf.png)
Till now everything is working great for the first stage as mentioned above. But for the `resources_babysitter` actions, I have to specify omited and monitor field. If I don't specify it, robusta sometime doesn't notify me about some changes.

**Comment by arikalon1** [comment]
By default, we omit the 'replicas' changes, because on clusters with HPA (Horizontal Pod Autoscaler), it might become spammy.
If you do want to see it, you need to override the default 'omitted_fields' parameter: 
Just add it to the action parameters:
omitted_fields: ["status", "metadata.generation","metadata.resourceVersion","metadata.managedFields"]
These are the defaults, just without the 'replicas' field.

**Comment by tuananh2508** [comment]
![image](https://user-images.githubusercontent.com/66721505/153141889-f15249b1-f09c-4354-b3e3-8ff4a6fdba85.png)
Also the NodeEnricher is not working right now.

**Comment by arikalon1** [comment]
Can you please send the out of 'robusta logs', after triggering the node enricher?

**Comment by tuananh2508** [comment]
@arikalon1 Here: https://pikab.in/78788d9feb

**Comment by arikalon1** [comment]
Do you know if there are pods running on that specific node?

**Comment by tuananh2508** [comment]
There are 18 pods runnign on that node on different namespaces:
![image](https://user-images.githubusercontent.com/66721505/153164322-01effcc9-e9e8-4b20-96eb-5cf3dc6d4f43.png)

**Comment by arikalon1** [comment]
I looked into this and figured out the problem.

Currently we don't send tables to the telegram sink, because the tables are too wide to be rendered properly on a mobile device. The output of this playbook is in a table, and that's the reason you don't see it in telegram.

Any ideas for how to fix this? We could add a placeholder like "<open UI to see data>" or we could find alternative way to render the tables so it looks OK. Open to ideas.

![telegram-table](https://user-images.githubusercontent.com/19672799/153173093-4efc3437-4f1e-479b-9d20-faba08bb330b.jpeg)

**Comment by tuananh2508** [comment]
I think for Telegram, maybe this kind of table can be paste to a .txt file. Just like what you're doing right now with Crash Pod event.

**Comment by arikalon1** [comment]
Sounds like a good solution for me.
Will fix it soon.
Thanks for the input

**Comment by tuananh2508** [comment]
Hope to hear from you soon ! 👯

**Comment by arikalon1** [comment]
Thanks for bringing it up.
The resource name is taken from the deployment metadata name and namespace.
What are the metadata name and namespace for the changed deployment?

**Comment by arikalon1** [comment]
Can you share the output of `kubectl get deployment -o yaml ..` for the relevant deployment?

**Comment by tuananh2508** [comment]
> Can you share the output of `kubectl get deployment -o yaml ..` for the relevant deployment?
```
→ k get deployments.apps -n staging cloud-dns-backend -o yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-11T04:03:22Z"
  generation: 13
  labels:
    app: wonder-app <- this one a manually add it
    app.kubernetes.io/instance: hn-staging-wonder-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wonder-app
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: wonder-app-0.1.0
....
```

**Comment by arikalon1** [comment]
Thank you.
It might be a bug indeed. 
Will check and update.

**Comment by arikalon1** [comment]
We couldn't replicate it locally.
Setting the following did trigger the change notification:
```
- triggers:
  - on_deployment_all_changes:
      labels_selector: app.kubernetes.io/instance=hn-staging-wonder-app
  actions:
  - resource_babysitter:
      omitted_fields:
        - metadata
```

Are you sure the label appears in the Deployment metadata, and not in the Pod template?
