### ISSUE TITLE
Jira Integration: Add project_override similar to slack's channel_override

### ISSUE THREAD

**Issue by ivankovnatsky** [robusta-dev/robusta#1659]
**Is your feature request related to a problem?**

I think it's more or less self explanatory, but to reiterate, we want to route the Jira issue creation into specific team's Jira projects. 

**Describe the solution you'd like**

Similar to what slack sink has with it's `channel_override`.

**Describe alternatives you've considered**

Create separate Jira project and issue type for specific robusta jira alerts.

**Additional context**

Consider this config example:

```yaml
clusterName: 
sinksConfig:
  - robusta_sink:
      name: robusta_ui_sink
      token: 
  - slack_sink:
      name: prod_infra_alerts
      slack_channel: 
      channel_override: "${labels.app.owner}-prod"
      api_key: 
      match:
        severity: [LOW, MEDIUM, HIGH]
...
  - jira_sink:
      name: 
      url: 
      username: 
      api_key: 
      dedups:
        - fingerprint
      project_override: "${labels.app.jira_project}"
      issue_type: 
      priority_mapping:
        HIGH: "High"
        MEDIUM: "Medium"
        LOW: "Low"
        INFO: "Lowest"
      match:
        severity: [LOW, MEDIUM, HIGH]
...
```
