### ISSUE TITLE
Ask Holmes Button Not Working in Mattermost

### ISSUE THREAD

**Issue by yudeye** [robusta-dev/robusta#1671]
I’ve noticed that the "Ask Holmes" button currently seems to be supported only in Slack, but it doesn't appear to work in Mattermost. One of the most exciting features of Robusta for me is the ability to click the "Ask Holmes" button in Slack and receive AI-driven analysis directly in the interface. However, this button does not show up in Mattermost.

Could you please clarify if the "Ask Holmes" button is only supported in Slack? If so, is there a plan to support Mattermost in the future, or is there a configuration issue preventing it from appearing?

Thank you for your help!

Here are some screenshots and helm configurations: 
![image](https://github.com/user-attachments/assets/3a7eda25-1bd8-43d3-b1e4-08828279e21d)

![image](https://github.com/user-attachments/assets/e0d8d1f2-608d-4352-9337-a8efef32081e)

```yaml
  sinksConfig:
    - mattermost_sink:
        name: personal_mattermost_sink
        url: https://mattermost.xxx.xxx
        token: xxxxxxx
        token_id: xxxxxx
        channel: robusta
    - slack_sink:
        name: main_slack_sink
        slack_channel: robusta_no_ui
        api_key: xxxxxx
```

**Comment by cooper-car** [comment]
Hi, @yudeye 

Can I ask how to successfully use the "Ask Holmes" button in Slack? 
The "Ask Holmes" button appears, but clicking on it doesn't respond.

![CleanShot 2025-01-05 at 18 03 35@2x](https://github.com/user-attachments/assets/b0b8d5e9-e4fe-4261-aed9-9bfeb7d00f25)



```
sinksConfig:
- slack_sink:
    name: main_slack_sink
    slack_channel: robusta-notifications
    api_key: xxxx

enableHolmesGPT: true
holmes:
  additionalEnvVars:
  - name: MODEL
    value: gpt-4o
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: holmes-secrets
        key: openAiKey
```
