### ISSUE TITLE
Remove the "View Graph" button from the Slack alert

### ISSUE THREAD

**Issue by Bobses** [robusta-dev/robusta#1721]
**Describe the bug**
The "View Graph" button appears even if the Robusta UI is not used (Robusta 0.20.0 - helm chart installed on EKS). 

**Expected behavior**
This button must be optional because it can mislead some users.

**Screenshots**
![Image](https://github.com/user-attachments/assets/0b680be3-7c27-42cb-80fa-ecbb6e53a56a)

**Desktop (please complete the following information):**
- Slack

**Additional context**
If the Robusta UI isn't used, the user must be able to remove that button.

**Comment by moshemorad** [comment]
Hi @Bobses, thanks for reaching out.

You can disable it by adding `prefer_redirect_to_platform: false` to the relevant sink config.
Please confirm it works for you.

I'm also going to add it to the official docs & push small fix that this will be the default behavior if Robusta UI isn't enabled.

**Comment by Bobses** [comment]
Hi @moshemorad ,

I added `prefer_redirect_to_platform: false` to the sink configuration, but it doesn't work - the alerts still have that button.

Here is my sink configuration:

```
sinksConfig:
- slack_sink:
    name: main_slack_sink
    prefer_redirect_to_platform: false
    slack_channel: robusta-alerts
    api_key: [...]
    scope:
      exclude:
        - namespace: apps
```
