### ISSUE TITLE
Ask Holmes button doesn't respect channel override

### ISSUE THREAD

**Issue by Amr-Aly** [robusta-dev/robusta#1752]
**Describe the bug**
We have the following config:

```
  sinksConfig:
    - slack_sink:
        name: main_slack_sink
        slack_channel: channelA
        channel_override: "${annotations.service/channel}"
```

When we click on Ask Holmes button in the service channel, the results get posted in `channelA`, not respecting the channel_override.

**Expected behavior**
Results get posted in the service channel.
