### ISSUE TITLE
Send resource creations and deletions to the Robusta UI, not just modifications

### ISSUE THREAD

**Issue by aantn** [robusta-dev/robusta#199]
Today we don't send resource creations/deletions to the Robusta UI. We should send them because they add useful information.

The relevant code to change is in `values.yaml`. The change is *probably* trivial, but it requires testing. If you work on this, please document any manual testing that you did to verify this works.

Relevant code in values.yaml:

```yaml
platformPlaybooks:
- triggers:
    - on_deployment_update: {}
  actions:
    - resource_babysitter: {}
  sinks:
    - "robusta_ui_sink"
- triggers:
    - on_daemonset_update: {}
  actions:
    - resource_babysitter: {}
  sinks:
    - "robusta_ui_sink"
- triggers:
    - on_statefulset_update: {}
  actions:
    - resource_babysitter: {}
  sinks:
    - "robusta_ui_sink"
```

See also: https://docs.robusta.dev/master/catalog/triggers/kubernetes.html
