### ISSUE TITLE
Routing messages

### ISSUE THREAD

**Issue by zhelyan** [robusta-dev/robusta#266]
Hi,

thank you for the great tool! 

We might be able to contribute on the feature request below but I wanted to first check if you had any thoughts, design concerns or suggestions:

It would be nice to be able to route the robusta messages similarly to how alertmanger does it.
Here's an example for Slack:

```
- slack_sink:
    name: prod_alerts
    match:
       namespace: prod-*
    slack_channel: prod-issues
 ```

would send messages where `namespace` matches `prod-*` to the `prod-issues` slack channel.
Ideally it should be possible to match against all attributes of the `Finding` [class](https://github.com/robusta-dev/robusta/blob/master/src/robusta/core/reporting/base.py#L60-L65)

thanks!

**Comment by aantn** [comment]
Hey, sounds great to me! We'd love to get a PR for this.

@arikalon1 any notes regarding implementation?

**Comment by arikalon1** [comment]
Thank you for the kind words @zhelyan :)
I like the idea very much as well.

What are your thoughts about the syntax here?
Is it full regex match? only simple wildcard (*)? maybe just contains or simple prefix?
And regarding namespace/kind/name, these are all mapped to the finding subject, right?

**Comment by zhelyan** [comment]
Regex sounds reasonable to me too.
 
I _think_ the general use case here is conditional forwarding, not routing. Routing implies that you have 1 sink and multiple internal destinations but some sinks, e.g datadog don't really work like that - there's one DD account with no option to "route" messages to e.g account members:

```
- datadog_sink:
    name: datadog_sink
    match:
        namespace: prod-.*
    api_key: "datadog api key"
```
