### ISSUE TITLE
Secure addition of private SSH key for private git repository with custom playbooks

### ISSUE THREAD

**Issue by dennislapchenko** [robusta-dev/robusta#307]
**Is your feature request related to a problem? Please describe.**
https://docs.robusta.dev/master/user-guide/configuration.html#loading-additional-playbooks 
Describes how to add an SSH key, but this aint a secure way for kubernetes manifests.

**Describe the solution you'd like**
I would like to create a kubernetes secret with the key which can be later mounted onto Robusta deployment.

**Describe alternatives you've considered**
Checking [helm templates](https://github.com/robusta-dev/robusta/blob/master/helm/robusta/templates/runner.yaml) found this:
```
      volumes:
        - name: playbooks-config-secret
          secret:
            secretName: robusta-playbooks-config-secret
            optional: true
```
Not sure this is what I need or how to use it.

Have found the proper doc section on passing secret values. But its proving hard to add the key correctly. 
Due to multiline nature of the keys - cant figure out how to add indentation. Was hoping its jinja2, so something like `{{ .. | indent(6, True) }}` could do, but its not, found = `env_values = re.findall(r"{{[ ]*env\.(.*)[ ]*}}", value)`.Oneliner key (with explicit `\n`) isnt working either, not is full concatennation.
This is what I've added:

`kubectl create secret generic ssh-keys --from-file=id_rsa=/path/to/.ssh/id_rsa`

`values.yaml:`
 ```
additional_env_vars:
  - name: GITHUB_SSH_KEY
    valueFrom:
      secretKeyRef:
        name: ssh-key
        key: id_rsa

playbookRepos:
  my_extra_playbooks:
    url: "git@github.com:private/repo.git"
    key: "{{ env.GITHUB_SSH_KEY }}"
```
If there is working way to add multiline - please let me know.
