### ISSUE TITLE
Silencing alerts in robusta config not working

### ISSUE THREAD

**Issue by omfurman** [robusta-dev/robusta#334]
I went with the docs - https://docs.robusta.dev/master/catalog/actions/event-enrichment.html?highlight=silence 
and added some alerts I would like to silence in the values.yaml of the installation like this:

```enablePrometheusStack: true
customPlaybooks:
- triggers:
  - on_prometheus_alert: {}
  actions:
  - name_silencer: 
      names:
      - "CPUThrottlingHigh"
   ```
It seemed to be working, but I'm getting alerts like this all the time:
![image](https://user-images.githubusercontent.com/90138173/169699166-85d11774-cdef-4bef-bf40-13249321ffb3.png)
Am I missing something?

**Comment by Avi-Robusta** [comment]
Hey,
Can you run: 
`robusta logs --namespace NAMESPACE_HERE | grep -in CPUThrottlingHigh`
Im expecting there to be some logs that say "silencing alert CPUThrottlingHigh"

**Comment by omfurman** [comment]
Sure, its returning the following output:
```194:2022-05-22 13:55:43.066 INFO     Successfully loaded Kubernetes resource storybook-xxxx for alert CPUThrottlingHigh
195:2022-05-22 13:55:43.184 INFO     Successfully loaded Kubernetes resource storybook-xxx for alert CPUThrottlingHigh
196:2022-05-22 13:55:43.200 INFO     Successfully loaded Kubernetes resource storybook-xxxx for alert CPUThrottlingHigh ```

**Comment by Avi-Robusta** [comment]
Hey @omfurman  , can you quickly run `robusta playbooks edit-config`, look on active_playbooks (and customPlaybooks) section, and see if you can spot your customPlaybook in there, and where is it located in relation to the other playbooks?

I'm thinking maybe we have some ordering issue where your playbook is placed after the alert reporting playbooks

**Comment by omfurman** [comment]
@Avi-Robusta Its located at the very end of the list and the config file, I can also see its after a CpuThrottling action:

```
 - actions:
    - cpu_throttling_analysis_enricher: {}
    - alert_graph_enricher:
        item_type: Pod
        resource_type: CPU
    triggers:
    - on_prometheus_alert:
        alert_name: CPUThrottlingHigh
  - actions:
    - deployment_status_enricher: {}
    triggers:
    - on_prometheus_alert:
        alert_name: KubernetesDeploymentReplicasMismatch
  - actions:
    - default_enricher: {}
    triggers:
    - on_prometheus_alert: {}
  - actions:
    - name_silencer:
        names:
        - CPUThrottlingHigh
    triggers:
    - on_prometheus_alert: {}
    ```
