### ISSUE TITLE
Resolved Alert Handling

### ISSUE THREAD

**Issue by vmusaely** [robusta-dev/robusta#345]
I've pushed `kill_pod` action to robusta runner pod, when I'm getting crashed pod it works fine and deletes that pod, after that the new one is created. But it runs the action even on messages that say “[RESOLVED]”, and deletes new created healthy pod.

**Comment by arikalon1** [comment]
Hi @vmusaely ,

I think you can achieve what you need by filtering the alert trigger only on firing alerts (and not resolved)

Your playbook configuration in your `values.yaml` file should be:
```
- triggers:
  - on_prometheus_alert:
      alert_name: YOUR CRASHING POD ALERT NAME
      status: "firing"
  actions:
  - kill_pod: {}
```

Does that work for you?
