### ISSUE TITLE
Silencing alerts in general

### ISSUE THREAD

**Issue by SohumB** [robusta-dev/robusta#376]
I see that you can silence prometheus alerts in the documentation, but it'd be good to be able to silence alerts in general. For instance, in our usecase, the platform playbook that hooks into `on_kubernetes_warning_event_create` produces a few warning events that can get spammy and aren't relevant to us, like `TooManyPods` (as we're expecting node autoscalers to kick in if that ever becomes an issue).

**Comment by arikalon1** [comment]
@SohumB , in order to change the behavior of the warning events playbook, you'll have to override the `platformPlaybooks` section in your `generated_values.yaml` file:
```
platformPlaybooks:
- triggers:
  - on_kubernetes_warning_event_create:
      exclude: ["NodeSysctlChange", "TooManyPods"]
  actions:
  - event_report: {}
  - event_resource_events: {}
  sinks:
    - "robusta_ui_sink"
- triggers:
    - on_deployment_all_changes: {}
    - on_daemonset_all_changes: {}
    - on_statefulset_all_changes: {}
  actions:
    - resource_babysitter: {}
  sinks:
    - "robusta_ui_sink"
```
