### ISSUE TITLE
Is there a way to specify the Slack Instance URL in order to use a different compatible endpoint like Mattermost?

### ISSUE THREAD

**Issue by m0sh1x2** [robusta-dev/robusta#437]
I am trying to find a way to set up an endpoint_url for the Slack Sink that might work with any compatible endoints like Mattermost:

```yaml
sinks_config:
# slack integration params
- slack_sink:
    slack_webhook_url: https://EXAMPLE_SLACK_URL.here.com
    name: main_slack_sink
    api_key: MY SLACK KEY
    slack_channel: MY SLACK CHANNEL
```

There is a similar integration with Grafana alerts https://docs.mattermost.com/scale/performance-alerting.html#mattermost-performance-alerting-guide that I am using but unfortunately I do not understand Python and won't be able to contribute unless I try for a few weeks.
