### ISSUE TITLE
HPA scale callback function name and namespace missing

### ISSUE THREAD

**Issue by alikhanxgrid** [robusta-dev/robusta#439]
**Describe the bug**
When a user receives a notification on slack to scale max replicas of an HPA and the user clicks on the button triggering the callback function, the max replicas of HPA is not increased instead an error is shown in robusta logs that name and namespace is missing. 

**To Reproduce**

1. Set up a cluster using kind. You can simply run _"kind create cluster"_ or create your own custom configuration.
Custom configuration used by me: 
```
# single node cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  # configure controller-manager bind address
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  # configure etcd metrics listen address
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: http://0.0.0.0:2381
  # configure scheduler bind address
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
- |-
  kind: KubeProxyConfiguration
  # configure proxy metrics bind address
  metricsBindAddress: 0.0.0.0
nodes:
- role: control-plane
```
2. Create a deployment and service. 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
```
3. Run ```kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=2 ```  to create an HPA for the deployment.

4. Add and upgrade your Robusta installation 
```
customPlaybooks:
- triggers:
   - on_horizontalpodautoscaler_update: {}   
  actions:
   - alert_on_hpa_reached_limit: {}
   ```
5. Run ```kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done" ``` to generate load on your pods forcing HPA to increase replicas.

6. After you have received notification on your slack to scale max replicas. Click on the button and run ```robusta logs``` to see the error.

**Expected behavior**
After clicking the button when you have received notification on slack to increase max replicas the callback function should increase max replicas to 3.

**Screenshots**
![image](https://user-images.githubusercontent.com/107905592/180415342-2a9c28b6-4f37-430c-8210-d03c8140f666.png)
Error above in text format:
```
2022-07-22 06:07:38.625 INFO     Callback `scale_hpa_callback` max_replicas: 3
2022-07-22 06:07:38.625 ERROR    Failed to create execution instance for scale_hpa_callback <class 'robusta.integrations.kubernetes.autogenerated.events.HorizontalPodAutoscalerAttributes'> {'max_replicas': 3, 'named_sinks': ['main_slack_sink']} Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/robusta/core/playbooks/playbooks_event_handler_impl.py", line 146, in run_external_action
    instantiation_params = action_def.from_params_parameter_class(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for HorizontalPodAutoscalerAttributes
name
  field required (type=value_error.missing)
namespace
  field required (type=value_error.missing)
  ```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS 64-bit
 - Browser Google Chrome
 - Version Version 103.0.5060.134 (Official Build) (64-bit)

**Additional context**
HPA example used from [https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/](url)
