### ISSUE TITLE
Explain TargetDown alerts related to coredns and kubedns

### ISSUE THREAD

**Issue by Sheeproid** [robusta-dev/robusta#553]
**Is your feature request related to a problem?**
kube-prometheus-stack that is being used by Robusta, monitors **coreDns** service by default.
(**[coreDns](https://coredns.io/)** is a service that handles dns on the cluster.)

However, on some Kubernetes distributions (e.g [GKE](https://cloud.google.com/kubernetes-engine)) **kubeDns** is used intstead of **coreDns**.
In that case, Robusta will fire "TargetDown" alerts from Prometheus which are not relevant, because the target **coreDns** should not exist in the first place.

The way for Robusta users to solve this is to define the following in their Robusta `generated_values.yaml` file:
```
kube-prometheus-stack:
  coreDns:
    enabled: false
  kubeDns:
    enabled: true
```

**Describe the solution you'd like**
Create an enricher (action) explains the situation so the Robusta users won't worry, and also how to fix it.
The enricher should first check if kubeDns actually exists on the cluster.

This should be its message:
"
This alert happens because Prometheus is trying to scrape **coreDns** service but that service does not exist in your cluster.
Robusta detects that **kubeDns** exists on your cluster, so this is safe to ignore and you can disable this alert by adding the following YAML to your Robusta configuration:
```
kube-prometheus-stack:
  coreDns:
    enabled: false
  kubeDns:
    enabled: true
```
"
