### ISSUE TITLE
Load Environment Variables when setting up an "https://" Playbooks Repo

### ISSUE THREAD

**Issue by prannonpendragas** [robusta-dev/robusta#755]
**Is your feature request related to a problem?**
The Remote Playbooks feature looks great, but it has some debilitating limitations. The allowed repo URL prefixes do not allow me to clone a remote repo from the software that my org is using.

I have a playbooks repo set up in [Gerrit](https://www.gerritcodereview.com/), and anonymous cloning over HTTP is disabled. That is, all repos are private by default. Cloning over SSH requires that I use the prefix "ssh://${username}@" and "git@" is not permitted.

I _would_ attempt to clone using the "https://" prefix instead, since it is possible (though not necessarily good practice) to clone using "https://${username}:${password}@repo". I actually tried this by adding some "additional_env_vars" to my helm values at installation time, like so:

```
cat << EOF >> /mnt/generated_values.yaml
runner:
  additional_env_vars:
  - name: GERRIT_USER
    valueFrom:
      secretKeyRef:
        name: robusta-gerrit
        key: user
  - name: GERRIT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: robusta-gerrit
        key: password
playbookRepos:
  my_extra_playbooks:
    url: "https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo"
EOF
```

I do see the environment variables show up when the runner starts, and the runner does try to use this URL, but the variables are not evaluated. This doesn't work because (I think) the app doesn't load environment variables before it tries to initialize the repo. My review of the code makes it look like the environment is only loaded after the repo is initialized.

So, in essence, my org's default Git management solution is hard excluded. This is not ideal.

**Describe the solution you'd like**
SOLUTION ONE:
Github allows you to authenticate to private repos using personal access tokens, which can be specified in the cloning URL. https://docs.github.com/en/rest/overview/other-authentication-methods?apiVersion=2022-11-28

So does Gitlab: https://stackoverflow.com/questions/25409700/using-gitlab-token-to-clone-without-authentication

And Gerrit allows me to clone with a username and password in the URL as well.

It seems to me that it would be a short lift and a big feature boost for private repos over HTTPS if we could load environments variables before initializing the playbook repository. 

Prior to install time, we could put the appropriate credentials into a kubernetes secret, and at install time we could add the appropriate configurations (as noted above) to the values that would load the environment into the runner and then have the runner try to clone from there.

SOLUTION TWO:
Add "ssh://" to the list of legal repo prefixes. This will probably be easier to implement than Solution One, though it keeps the existing limitations on what https based git URLs can do.

**Describe alternatives you've considered**
The easiest thing for me to do is to set up a private Playbooks repo in github after all and then go from there.

On principle, though, it seems more favorable to me to enable this functionality for as wide a set of software as possible as long as it is not too heavy a lift.

**Additional context**
N/A

**Comment by arikalon1** [comment]
Thanks for reporting it @prannonpendragas 
In your example you addded:
```
"https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo"
```

The Robusta env var replacement syntax is: {{ env.SOME_VAR_NAME }}
Can you try:
```
"https://${env.GERRIT_USER}:${env.GERRIT_PASSWORD}@repo"
```

**Comment by prannonpendragas** [comment]
> Thanks for reporting it @prannonpendragas In your example you addded:
> 
> ```
> "https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo"
> ```
> 
> The Robusta env var replacement syntax is: {{ env.SOME_VAR_NAME }} Can you try:
> 
> ```
> "https://${env.GERRIT_USER}:${env.GERRIT_PASSWORD}@repo"
> ```

So, I tried this out. This did not work. Oddly enough, I got different errors this time than I did the last time that I tried this.

I first tried what you suggested with the configuration:
```
    url: "https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo"
```

I received this error:
```
2023-03-02 15:11:33.225 INFO     Cloning git repo https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo. repo name repo
2023-03-02 15:11:34.220 ERROR    running command ['git', 'clone', 'https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo', '/app/robusta-git/repo'] failed with returncode=128
2023-03-02 15:11:34.221 ERROR    stdout=
2023-03-02 15:11:34.221 ERROR    stderr=Cloning into '/app/robusta-git/repo'...
remote: Unauthorized
fatal: Authentication failed for 'https://repo/'

2023-03-02 15:11:34.221 ERROR    Failed to add playbooks repo my_extra_playbooks
Traceback (most recent call last):
  File "/app/src/robusta/runner/config_loader.py", line 111, in __load_playbooks_repos
    repo = GitRepo(
  File "/app/src/robusta/integrations/git/git_repo.py", line 70, in __init__
    self.init_repo()
  File "/app/src/robusta/integrations/git/git_repo.py", line 133, in init_repo
    self.__exec_git_cmd(["git", "clone", self.git_repo_url, self.repo_local_path])
  File "/app/src/robusta/integrations/git/git_repo.py", line 121, in __exec_git_cmd
    raise Exception(f"Error running git command: {cmd}")
Exception: Error running git command: ['git', 'clone', 'https://${GERRIT_USER}:${GERRIT_PASSWORD}@repo', '/app/robusta-git/repo']
```

I then tried it using this configuration:
```
    url: "https://$GERRIT_USER:$GERRIT_PASSWORD@repo"
```

I got essentially the same error, just with different literal strings.

I then tried it using this configuration:
```
    url: "https://{{ env.GERRIT_USER }}:{{ env.GERRIT_PASSWORD }}@repo"
```

Same error.

Previously, when I had been trying this out, I got errors indicating that the environment variables could not be found, or I saw that the variables in the URL string were being evaluated to empty strings, so these new errors are a bit weird to me.

I have a feeling that maybe since I am populating my generated_values.yml file with this configuration using `cat << 'EOF' >> /mnt/generated_values.yml` rather than editing the values file directly, it might be causing some sort of weird behavior? But no idea.

In any case, the behavior from robusta is not ideal. What are your further thoughts?

**Comment by arikalon1** [comment]
Thank you @prannonpendragas 
I'll add the support for:
```
   url: "https://{{ env.GERRIT_USER }}:{{ env.GERRIT_PASSWORD }}@repo"
```

**Comment by prannonpendragas** [comment]
Great news @arikalon1 ! Once you have added the support, I am happy to test it in my environment.

**Comment by arikalon1** [comment]
@prannonpendragas 
Would this be sufficient for you:
```
url: "{{ env.REPO_URL_WITH_CREDS }}"
```

Meaning, that in your secret you'll have:
url: https://user:pass@repo

**Comment by prannonpendragas** [comment]
That might work, yeah. What would the implementation look like precisely? @arikalon1

**Comment by arikalon1** [comment]
In the `generated_values.yaml`:
```
runner:
  additional_env_vars:
  - name: USER_REPO_URL
    valueFrom:
      secretKeyRef:
        name: robusta-gerrit
        key: url
playbookRepos:
  my_extra_playbooks:
    url: "{{ env.USER_REPO_URL}}"
```

Inside the `robusta-gerrit` secret, the `url` key should have:
"https://user:password@repo"

Will that work?

**Comment by prannonpendragas** [comment]
I'll try this method tomorrow @arikalon1 , but on first review I have doubts that this will work, since in previous examples the whole problem is that the environment variable is not evaluated when Robusta tries to initialize the Git repo.

I'll let you know how it goes, though. :)

**Comment by prannonpendragas** [comment]
> @prannonpendragas I wasn't suggesting it's working at the moment. It's not. I was asking, if this kind of fix will satisfy your requirements

Ah! Please forgive my misunderstanding.

Yes, that would satisfy my requirement. It's simple in the configuration file and fits my use case nicely. :)

**Comment by arikalon1** [comment]
Added the option to pull the playbookRepo url from an environment variable
For example:
```
playbookRepos:
  chatgpt_robusta_actions:
    url: "{{ env.REPO_URL }}"
runner:
  additional_env_vars:
    - name: REPO_URL
      value: "https://github.com/robusta-dev/kubernetes-chatgpt-bot.git"
```

It will be available on the next release (0.10.13)

The changes are available in this image if you'd like to test it:
`us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:load_repo_url_from_env`

To use it, add to your values:
```
runner:
  image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:load_repo_url_from_env
```

**Comment by prannonpendragas** [comment]
This worked @arikalon1 . As a reference for future documentation, this is what I did.

- Created secret with URL, credentials embedded.
```
kubectl create secret generic robusta-gerrit --from-literal=url="https://username:password@repo"
```

- Added config to generated_values.yaml.
```
cat << EOF >> /mnt/generated_values.yaml
runner:
  image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/robusta-runner:load_repo_url_from_env
  additional_env_vars:
  - name: REPO_URL
    valueFrom:
      secretKeyRef:
        name: robusta-gerrit
        key: url
playbookRepos:
  my_extra_playbooks:
    url: "{{ env.REPO_URL }}"
EOF
```

And then the runner successfully cloned the repo. :) This adds functionality for private HTTPS repos, which is very good.

Thanks again!
