### ISSUE TITLE
Robusta not sending all events

### ISSUE THREAD

**Issue by Rez0k** [robusta-dev/robusta#799]
Hi,

I am using Robusta version 0.10.14
I am sending all kubernetes warning events to a slack channel, and I noticed not all events are being sent.
For example, I can see events about some failed readiness probe events, but not all readiness probe events are being sent to my slack channel.

My config:
```
customPlaybooks:
- triggers:
      - on_kubernetes_warning_event: {}
      - on_kubernetes_warning_event_create: {}
      - on_kubernetes_warning_event_update: {}
      - on_kubernetes_warning_event_delete: {}
    actions:
      - event_report: {}
      - event_resource_events: {}
``` 
I tried different versions of this config but nothing helped.

Is this a bug or did I miss something in my config?

Any idea?

**Comment by arikalon1** [comment]
Thanks for reporting it @Rez0k 

I think you want to use only the `on_kubernetes_warning_event` trigger. It includes all the others.
In addition, by default, in order to prevent too many identical events, there's `rate_limiting`
So, if the same event fires on the same resource, it will be sent only once an hour by default.
However, you can override the configuration.

Can you try using:
```
customPlaybooks:
  - triggers:
      - on_kubernetes_warning_event: 
          rate_limit: 0
    actions:
      - event_report: {}
      - event_resource_events: {}
```

Does that solves your issue?
