### ISSUE TITLE
Send events with balanced rate limit

### ISSUE THREAD

**Issue by Rez0k** [robusta-dev/robusta#802]
Hi,

I am trying to send all kubernetes warning events to a slack channel.
At first, not all events were sent to my channel (for example, some readiness probes were sent and some were not), I disabled the rate_limit, and all the events were sent as I wanted.
But then I saw why the rate_limit is important (image below)

![image](https://user-images.githubusercontent.com/23296337/228764482-9ead43f7-0130-4f0c-89cf-0cdafe268b2f.png)

I want to find a balance, I want all the readiness/liveness probes and maybe other events to be in my slack channel without any rate limit, but other events like FailedMount to be sent with a rate limit.

How can I achieve this kind of behavior with my current config?

```
customPlaybooks:
- triggers:
      - on_kubernetes_warning_event:
          rate_limit: 30
          exclude: ["NodeSysctlChange", "TooManyPods"]
    actions:
      - event_report: {}
      - event_resource_events: {}
```

One more question: does the config of - 
```
- triggers:
  - on_kubernetes_warning_event_create:
      exclude: ["NodeSysctlChange", "TooManyPods"]
```
excluding events by a string or by event name?
For example, if I will write `exclude: ["newrelic"]` any events that contain the word newrelic will be excluded?
