### ISSUE TITLE
MS Teams webhook returning status 400

### ISSUE THREAD

**Issue by mxk6n** [robusta-dev/robusta#841]
## Describe the bug
My MS Teams webhook suddenly stopped working recently.

When checking the logs of the robusta runner I got the following error:

```
ERROR    Failed to send message to teams. error: Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 400 with ContextId MS-CV=<CONTEXT_ID> message: <MESSAGE_DATA>
```

I then took `<MESSAGE_DATA>` and tried to post it to the webhook manually to see what the problem might be:

```
curl -X POST -H "Content-Type: application/json" -d @./message-data.json <WEBHOOK_URL>
```

which basically resulted in the same error as in the logs above (no further info).

First I thought it might be the message limit for MS Teams webhooks (28kB) that could be the problem, but it wasn't.

In the end it seemed like the severity emoji in the title ("🔴") was the problem:

```
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null,
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.2",
        "msTeams": {
          "width": "full"
        },
        "body": [
          {
            "type": "TextBlock",
            "text": "🔴 HIGH - Job <JOB_NAME> in namespace <NAMESPACE> failed",
            "size": "extraLarge",
            "wrap": true
          }
        ]
      }
    }
  ]
}
```

did not work, while the following went through without any problems:

```
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null,
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.2",
        "msTeams": {
          "width": "full"
        },
        "body": [
          {
            "type": "TextBlock",
            "text": "HIGH - Job <JOB_NAME> in namespace <NAMESPACE> failed",
            "size": "extraLarge",
            "wrap": true
          }
        ]
      }
    }
  ]
}
```

Does anyone have an idea on how to fix this or knows a workaround for this issue?

Thanks in advance 🙏 

## Robusta Config

```
customPlaybooks:
- triggers:
  - on_job_failure: {}
      # namespace_prefix: robusta
  actions:
    - create_finding:
        aggregation_key: "job_failure"
        title: "Job $name in namespace $namespace failed"
    - job_info_enricher: {}
    - job_events_enricher: {}
    - job_pod_enricher: {}
```

## Expected behavior
MS Teams webhook should work as intended.
