### ISSUE TITLE
Allow the user to specify a branch/tag to clone when adding a playbookRepo

### ISSUE THREAD

**Issue by RoryDoherty** [robusta-dev/robusta#858]
**Is your feature request related to a problem?**
I would like to be able to specify different branches for cloning a playbook repo. This would allow me to have a stable branch that is used in prod clusters and also have a dev branch that can be used when testing out changes to some custom actions without affecting live clusters

**Describe the solution you'd like**
Add a new branch field under the custom playbook repo which would then be cloned by the runner instead of the default branch
```
  playbookRepos:
    my_playbook_repo:
      url: <repo_url>
      key: "{{env.GITHUB_SSH_KEY}}"
      branch: <branch_name>
```

**Describe alternatives you've considered**
I don't think there is an alternative to this
