### ISSUE TITLE
Support sink routing based on alert labels

### ISSUE THREAD

**Issue by djfinnoy** [robusta-dev/robusta#946]
**Is your feature request related to a problem?**
We are transitioning from routing alerts via Alertmanager where we had a label based routing strategy to get alerts to the appropriate Slack channels.

Every alert would have a `team` label, and this was used by Alertmanager to get the alert sent to the correct `route`.

In our new setup, all alerts will go to Robusta, and it becomes Robusta's responsibility to get alerts sent to the correct Slack channel. Based on the `sinkConfig` docs, I get the impession that Robusta's routing features are a bit more limited than those of Alertmanager:

The [currently supported match attributes](https://docs.robusta.dev/master/configuration/configuring-sinks.html#matches-can-be-lists-or-regexes)  would allow us to route many alerts to the correct team based on `namespace`, but we do have some resources where alerts destined for different teams originate from the same namespace (ArgoCD application out-of-sync being a notable example). I think adding labels as a match attribute would seal this hole in the sink routing logic.

**Describe the solution you'd like**
I would like alert labels to be incorporated as a match attribute so that I can do this:

```
  - slack_sink:
      name: backend-team
      slack_channel: alerts-backend
      api_key: "{{ env.SLACK_API_KEY }}"
      match:
        alert_labels:     # This field is not supported at right now
          team: backend   # This label comes from alertmanager
  - slack_sink:
      name: frontend-team
      slack_channel: alerts-frontend
      api_key: "{{ env.SLACK_API_KEY }}"
      match:
        alert_labels:
          team: frontend
```
